#!/usr/bin/env python3
"""
DOA Analysis Script
==================

Analyzes DOA estimation accuracy using aligned RTK ground-truth data.

Input:
    CSV generated by doa_vs_rtk_comparison.py

Output:
    - Diagnostic plots
    - Quantitative performance summary (median, std)
    - Grid saturation diagnostics

This script performs *analysis only*:
- No filtering of DOA estimation
- No recalculation of ground truth
"""

# ============================================================
# Imports
# ============================================================
import os
import csv
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# CONFIGURATION
# ============================================================

# Input file
INPUT_CSV = (
    "firmware/DOA_test/doa_vs_rtk_comparison/day4/"
    "doa_vs_rtk_test_S6.csv"
)


# ------------------------------------------------------------
# Filtering options
# ------------------------------------------------------------

# Minimum Z height (meters); set to None to disable
MIN_Z_M = 3.0

# Distance filtering (meters)
DISTANCE_THRESHOLD_M = 50.0
DISTANCE_MODE = "all"   # "all", "near", "far"

# ------------------------------------------------------------
# Plot options
# ------------------------------------------------------------

# Plot mode:
#   "single" → total error only
#   "three"  → total / azimuth / elevation
PLOT_MODE = "single"

# Marker sizes
SCATTER_SIZE = 14

# ============================================================
# Load data
# ============================================================

rtk_x = []
rtk_y = []
rtk_z = []

gt_az = []
gt_el = []

doa_az = []
doa_el = []

az_err = []
el_err = []
total_err = []

distance = []

with open(INPUT_CSV, "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        x = float(row["rtk_x_m"])
        y = float(row["rtk_y_m"])
        z = float(row["rtk_z_m"])

        az_e = float(row["az_error_deg"])
        el_e = float(row["el_error_deg"])

        r = np.sqrt(x**2 + y**2 + z**2)

        # ----------------------------------------------------
        # Filters
        # ----------------------------------------------------
        if MIN_Z_M is not None and z < MIN_Z_M:
            continue

        if DISTANCE_MODE == "near" and r >= DISTANCE_THRESHOLD_M:
            continue
        if DISTANCE_MODE == "far" and r < DISTANCE_THRESHOLD_M:
            continue

        rtk_x.append(x)
        rtk_y.append(y)
        rtk_z.append(z)

        az_err.append(az_e)
        el_err.append(el_e)
        total_err.append(np.sqrt(az_e**2 + el_e**2))

        distance.append(r)

rtk_x = np.array(rtk_x)
rtk_y = np.array(rtk_y)
rtk_z = np.array(rtk_z)

az_err = np.array(az_err)
el_err = np.array(el_err)
total_err = np.array(total_err)
distance = np.array(distance)

# ============================================================
# Grid saturation diagnostics
# ============================================================

ELEV_MIN = 0.0
ELEV_MAX = 90.0

boundary_hits = np.sum(
    (np.abs(el_err) < 1e-6) |
    (np.abs(np.abs(el_err) - ELEV_MAX) < 1e-6)
)

boundary_ratio = boundary_hits / len(el_err) if len(el_err) else 0.0

# ============================================================
# Statistics helpers
# ============================================================

def print_error_stats(label, mask, total_e, az_e, el_e):
    if np.sum(mask) == 0:
        print(f"{label}: No samples")
        return

    print(f"{label}:")
    print(f"  Samples          : {np.sum(mask)}")

    # -------------------------------
    # Total error
    # -------------------------------
    print(
        f"  Total error      : "
        f"median={np.median(total_e[mask]):.2f}°, "
        f"mean={np.mean(total_e[mask]):.2f}°, "
        f"std={np.std(total_e[mask]):.2f}°"
    )

    # -------------------------------
    # Azimuth error
    # (signed mean, abs median)
    # -------------------------------
    print(
        f"  Azimuth error    : "
        f"median={np.median(np.abs(az_e[mask])):.2f}°, "
        f"mean={np.mean(az_e[mask]):.2f}°, "
        f"std={np.std(az_e[mask]):.2f}°"
    )

    # -------------------------------
    # Elevation error
    # -------------------------------
    print(
        f"  Elevation error  : "
        f"median={np.median(np.abs(el_e[mask])):.2f}°, "
        f"mean={np.mean(el_e[mask]):.2f}°, "
        f"std={np.std(el_e[mask]):.2f}°"
    )

# ============================================================
# GOLD-STANDARD SUMMARY
# ============================================================

print("\n================ DOA PERFORMANCE SUMMARY ================\n")

mask_all = np.ones(len(total_err), dtype=bool)
mask_near = distance < DISTANCE_THRESHOLD_M
mask_far = distance >= DISTANCE_THRESHOLD_M

print_error_stats("ALL DISTANCES", mask_all, total_err, az_err, el_err)
print()
print_error_stats(f"DISTANCE < {DISTANCE_THRESHOLD_M} m", mask_near,
                  total_err, az_err, el_err)
print()
print_error_stats(f"DISTANCE ≥ {DISTANCE_THRESHOLD_M} m", mask_far,
                  total_err, az_err, el_err)

print(f"\nElevation grid boundary hits: {boundary_ratio*100:.1f}%")
if boundary_ratio > 0.1:
    print("⚠️  Significant elevation grid saturation detected")

print("\n=========================================================\n")

# ============================================================
# PLOT 1 — 3D RTK positions colored by total error
# ============================================================

def set_axes_equal(ax):
    """
    Set equal scaling for a 3D plot so that spheres appear as spheres,
    cubes as cubes, etc.
    """
    x_limits = ax.get_xlim3d()
    y_limits = ax.get_ylim3d()
    z_limits = ax.get_zlim3d()

    x_range = abs(x_limits[1] - x_limits[0])
    y_range = abs(y_limits[1] - y_limits[0])
    z_range = abs(z_limits[1] - z_limits[0])

    max_range = max(x_range, y_range, z_range)

    x_mid = np.mean(x_limits)
    y_mid = np.mean(y_limits)
    z_mid = np.mean(z_limits)

    ax.set_xlim3d([x_mid - max_range / 2, x_mid + max_range / 2])
    ax.set_ylim3d([y_mid - max_range / 2, y_mid + max_range / 2])
    ax.set_zlim3d([z_mid - max_range / 2, z_mid + max_range / 2])


fig = plt.figure(figsize=(7, 6))
ax = fig.add_subplot(111, projection="3d")

sc = ax.scatter(
    rtk_x, rtk_y, rtk_z,
    c=total_err,
    cmap="viridis",
    s=SCATTER_SIZE,
    vmin=0.0,
    vmax=180.0
)

ax.set_xlabel("X [m]")
ax.set_ylabel("Y [m]")
ax.set_zlabel("Z [m]")
ax.set_title("RTK Positions Colored by Total DOA Error")

ax.scatter(
    [0], [0], [0],
    color="red",
    s=80,
    marker="X",
    label="Base frame origin"
)
ax.legend(loc="best")

set_axes_equal(ax)

plt.colorbar(sc, label="Total DOA Error [deg]")
plt.tight_layout()
plt.show()

# ============================================================
# PLOT 2 — Error vs distance
# ============================================================

if PLOT_MODE == "three":
    fig, axs = plt.subplots(1, 3, figsize=(15, 4))

    axs[0].scatter(distance, total_err, s=SCATTER_SIZE, alpha=0.6)
    axs[0].set_title("Total Error vs Distance")
    axs[0].set_xlabel("Distance [m]")
    axs[0].set_ylabel("Error [deg]")
    axs[0].grid(True)

    axs[1].scatter(distance, az_err, s=SCATTER_SIZE, alpha=0.6)
    axs[1].set_title("Azimuth Error vs Distance")
    axs[1].set_xlabel("Distance [m]")
    axs[1].grid(True)

    axs[2].scatter(distance, el_err, s=SCATTER_SIZE, alpha=0.6)
    axs[2].set_title("Elevation Error vs Distance")
    axs[2].set_xlabel("Distance [m]")
    axs[2].grid(True)

    plt.tight_layout()
    plt.show()

else:
    plt.figure(figsize=(7, 4))
    plt.scatter(distance, total_err, s=SCATTER_SIZE, alpha=0.6)
    plt.xlabel("Distance [m]")
    plt.ylabel("Total Error [deg]")
    plt.title("DOA Error vs Distance")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# ============================================================
# PLOT 3 — Error histograms
# ============================================================

if PLOT_MODE == "three":
    fig, axs = plt.subplots(1, 3, figsize=(15, 4), sharey=True)

    axs[0].hist(total_err, bins=50)
    axs[0].set_title("Total Error")
    axs[0].set_xlabel("Error [deg]")
    axs[0].set_ylabel("Count")

    axs[1].hist(np.abs(az_err), bins=50)
    axs[1].set_title("Azimuth Error")
    axs[1].set_xlabel("Error [deg]")

    axs[2].hist(np.abs(el_err), bins=50)
    axs[2].set_title("Elevation Error")
    axs[2].set_xlabel("Error [deg]")

    plt.tight_layout()
    plt.show()

else:
    plt.figure(figsize=(7, 4))
    plt.hist(total_err, bins=50)
    plt.xlabel("Error [deg]")
    plt.ylabel("Count")
    plt.title("Total DOA Error Distribution")
    plt.tight_layout()
    plt.show()
